/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: MarproZ (https://sketchfab.com/MarproZ)
license: SKETCHFAB Editorial (https://sketchfab.com/licenses)
source: https://sketchfab.com/3d-models/pickle-rick-rick-and-morty-99ab8570705f4e0db247138adb4ff32f
title: Pickle Rick - Rick and Morty
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function PickleRick(props) {
  const { nodes, materials } = useGLTF("/pickle_rick_-_rick_and_morty.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.material_0}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/pickle_rick_-_rick_and_morty.glb");
